#!/bin/bash

#SBATCH --account=coastal
#SBATCH --job-name=FLOFS_adc_RUN
#SBATCH --time=02:30:00
#SBATCH -q batch
#SBATCH --ntasks=499
#SBATCH --cpus-per-task=1   # Number of cores per MPI rank (for hyperthreading)
##SBATCH --mail-user=USER@noaa.gov
##SBATCH --mail-type=ALL
#SBATCH --error=FLOFS_adc_RUN.err.log
#SBATCH --output=FLOFS_adc_RUN.out.log

set -e

source ${mod_loc:+${mod_loc}/}envmodules_intel.${PLATFORM}
module list

srun ${bin_loc:+${bin_loc}/}NEMS.x
