#!/bin/bash

#SBATCH --account=coastal
#SBATCH --job-name=FLSH_pam2adc_RUN
#SBATCH --time=02:30:00
#SBATCH -q batch
#SBATCH --mem 3000
#SBATCH --ntasks=11
#SBATCH --cpus-per-task=1   # Number of cores per MPI rank (for hyperthreading)
##SBATCH --mail-user=USER@noaa.gov
##SBATCH --mail-type=ALL
#SBATCH --error=FLSH_pam2adc_RUN.err.log
#SBATCH --output=FLSH_pam2adc_RUN.out.log

set -e

source ${mod_loc:+${mod_loc}/}envmodules_intel.hera
module list

srun ${bin_loc:+${bin_loc}/}NEMS.x
